title: Marcelo Rios
description: Welcome to my portfolio!
theme: just-the-docs

url: https://mrios38.github.io/portfolio/

aux_links:
  Repos: https://github.com/mrios38?tab=repositories

aux_links_new_tab: true
